spring:
  datasource:
    url: jdbc:mysql://localhsot:3306/sample?createDatabaseIfNotExist=true
    username: root
    password: piseth@2013
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl