spring:
  datasource:
    url: jdbc:mysql://brcyb9izxqmpjtgbfata-mysql.services.clever-cloud.com:3306/brcyb9izxqmpjtgbfata?createDatabaseIfNotExist=true
    username: uxd50eimfs7sovhk
    password: M3YVqllOwf2PbucW0Pze
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl